Fix cli package compatibility using Go Modules
Recently, the following errors have come up when building:

    $ go build
    # github.com/ksubedi/gomove
    ./main.go:18:5: app.Author undefined (type *cli.App has no field or method Author)
    ./main.go:21:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
      cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    ./main.go:26:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
      cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    ./main.go:30:17: cannot use cli.StringFlag literal (type cli.StringFlag) as type cli.Flag in array or slice literal:
      cli.StringFlag does not implement cli.Flag (Apply method has pointer receiver)
    ./main.go:37:13: cannot use func literal (type func(*cli.Context)) as type cli.ActionFunc in assignment

The `github.com/codegangsta/cli` package has been moved to
`github.com/urfave/cli`.

The latest major version of `github.com/urfave/cli` is now v2, which is
incompatible with the version `gomove` expects.

Add Go Modules manifest files with:

    $ go mod init

to set a dependency on `github.com/urfave/cli` v1, fixing the build
errors.

Fixes #6.